---
- name: "PLAY 1 - Conformité manager"
  hosts: manager
 
  tasks:
    - name: "Creation d'une paire de clés ssh sur manager"
      community.crypto.openssh_keypair:
        state: present
        type: ed25519
        path: id_ansible
        comment: manager@formation

- name: "PLAY 2 - config playbook"
  # Target : à qui s'adresse se PLAY
  hosts: linux
  become: true

  # Déclation du block tasks pour appeler des modules
  tasks:
    - name: "Ajout utilisateur"
      user:
        name: formation
        state: present
        uid: 1002
        # Utilisation d'une variable du fichier d'inventaire 
        group: "{{ sudogrp }}"

    - name: "Creation d'un fichier"
      copy:
        dest: /home/formation/fichier1
        content: "Mon fichier généré par ansible"
        owner: formation
        group: formation
        mode: '0644'